services:

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    volumes:
    - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    restart: on-failure

volumes:
  wordpress_data:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: "/Users/cefue/Cursus/inception_data/wordpress"
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/Users/cefue/Cursus/inception_data/mariadb"
networks:
  inception:
    driver: bridge 
